# Generated by Django 4.2.7 on 2023-12-04 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_user', models.TextField(blank=True, max_length=300, null=True, verbose_name='Информация')),
                ('gold', models.IntegerField(blank=True, default=2000, null=True, verbose_name='Деньги')),
                ('receiving_timer', models.DateTimeField(blank=True, null=True, verbose_name='Последнее получение')),
                ('win', models.IntegerField(blank=True, default=0, null=True, verbose_name='Победы')),
                ('lose', models.IntegerField(blank=True, default=0, null=True, verbose_name='Поражения')),
                ('is_activated', models.BooleanField(blank=True, default=True, null=True, verbose_name='Активен')),
                ('profile_pic', models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='image/profile/', verbose_name='Аватарка')),
                ('current_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.card', verbose_name='Выбранная карта')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
