# Generated by Django 4.2.7 on 2023-12-04 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_fighthistory_saleusercards'),
        ('users', '0003_alter_profile_current_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleStoreCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField(verbose_name='Дата и время')),
                ('sold_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.cardstore', verbose_name='Проданная карта')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.transactions', verbose_name='Транзакция')),
            ],
        ),
    ]
