# Generated by Django 4.2.7 on 2024-02-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_guild_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_guild_accession',
            field=models.DateField(blank=True, null=True, verbose_name='Дата присоединения к гильдии'),
        ),
        migrations.AddField(
            model_name='profile',
            name='guild_point',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Очки гильдии'),
        ),
    ]
