# Generated by Django 4.2.7 on 2024-02-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_guild_date_last_change_buff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='date_last_change_buff',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время смены усиления'),
        ),
    ]
