# Generated by Django 4.2.7 on 2024-07-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_guild_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='amulet_slots',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='Максимальное количество амулетов'),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_slots',
            field=models.IntegerField(blank=True, default=80, null=True, verbose_name='Максимальное количество карт'),
        ),
    ]
