# Generated by Django 4.2.7 on 2025-07-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_experience_bar_profile_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gold',
            field=models.IntegerField(blank=True, default=10000, null=True, verbose_name='Деньги'),
        ),
    ]
