# Generated by Django 4.2.7 on 2025-09-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_profile_gold'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='event_visit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Отметки пользователя для награды'),
        ),
    ]
