# Generated by Django 4.2.7 on 2025-09-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_profile_event_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_event_visit',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последней отметки для награды'),
        ),
    ]
