# Generated by Django 4.2.7 on 2025-09-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_profile_date_event_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='rating',
            field=models.PositiveIntegerField(verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='event_visit',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Отметки пользователя для награды'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lose',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Поражения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='win',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Победы'),
        ),
    ]
