# Generated by Django 4.2.7 on 2025-09-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_guild_rating_alter_profile_event_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='max_number_of_participants',
            field=models.IntegerField(blank=True, default=30, null=True, verbose_name='Максимальное количество участников'),
        ),
    ]
