# Generated by Django 4.2.7 on 2025-09-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_guild_max_number_of_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='max_number_of_participants',
            field=models.PositiveSmallIntegerField(blank=True, default=30, null=True, verbose_name='Максимальное количество участников'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='number_of_participants',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество участников'),
        ),
    ]
