# Generated by Django 4.2.7 on 2025-09-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_guild_max_number_of_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='amulet_slots',
            field=models.PositiveSmallIntegerField(blank=True, default=100, null=True, verbose_name='Максимальное количество амулетов'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='card_slots',
            field=models.PositiveSmallIntegerField(blank=True, default=80, null=True, verbose_name='Максимальное количество карт'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='event_visit',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Отметки пользователя для награды'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gold',
            field=models.PositiveIntegerField(blank=True, default=10000, null=True, verbose_name='Деньги'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Уровень'),
        ),
    ]
