# Generated by Django 4.2.7 on 2025-09-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_profile_amulet_slots_alter_profile_card_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='after',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='После'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='before',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='До'),
        ),
    ]
