# Generated by Django 4.2.7 on 2025-10-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_transactions_after_alter_transactions_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='diamond',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Кристалы'),
        ),
    ]
