# Generated by Django 4.2.7 on 2023-12-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_salestorecards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salestorecards',
            options={'verbose_name': 'Покупка в магазине', 'verbose_name_plural': 'Покупки в магазине'},
        ),
    ]
