# Generated by Django 4.2.7 on 2023-12-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_salestorecards_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salestorecards',
            options={'verbose_name': 'Покупка в магазине карт', 'verbose_name_plural': 'Покупки в магазине карт'},
        ),
        migrations.AddField(
            model_name='transactions',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='image/profile/avatar.jpg', null=True, upload_to='image/profile/', verbose_name='Аватарка'),
        ),
    ]
