# Generated by Django 4.2.7 on 2024-02-14 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_favoriteusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildBuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('numeric_value', models.FloatField(verbose_name='Числовое значение')),
            ],
            options={
                'verbose_name': 'Усиление гильдии',
                'verbose_name_plural': 'Усиления гильдии',
            },
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('number_of_participants', models.IntegerField(default=1, verbose_name='Количество участников')),
                ('guild_pic', models.ImageField(blank=True, default='image/guild/avatar.png', null=True, upload_to='image/guild/', verbose_name='Аватарка')),
                ('date_create', models.DateField(verbose_name='Дата создания')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('date_last_change_buff', models.DateTimeField(verbose_name='Дата и время смени усиления')),
                ('buff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.guildbuff', verbose_name='Усиление гильдии')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Лидер')),
            ],
            options={
                'verbose_name': 'Гильдия',
                'verbose_name_plural': 'Гильдии',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='guild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.guild', verbose_name='Гильдия'),
        ),
    ]
