# Generated by Django 4.2.7 on 2024-02-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_date_guild_accession_profile_guild_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='date_create',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='date_last_change_buff',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время смени усиления'),
        ),
    ]
