# Generated by Django 4.2.7 on 2024-02-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_guild_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='date_last_change_buff',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время смены усиления'),
        ),
    ]
