# Generated by Django 4.2.7 on 2024-07-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_amulet_slots_profile_card_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience_bar',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Опыт'),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Уровень'),
        ),
    ]
