# Generated by Django 4.2.7 on 2023-12-04 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_salestorecards_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0006_delete_saleusercards'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleUserCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.card', verbose_name='Карта')),
                ('salesman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesman', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
                ('transaction_buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_buyer', to='users.transactions', verbose_name='Транзакция покупателя')),
                ('transaction_salesman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_salesman', to='users.transactions', verbose_name='Транзакция продавца')),
            ],
            options={
                'verbose_name': 'Продажа карты пользователя',
                'verbose_name_plural': 'Продажи карт пользователей',
            },
        ),
    ]
