# Generated by Django 4.2.7 on 2023-12-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_experienceitems_usersinventory_historypurchaseitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experienceitems',
            options={'verbose_name': 'Предмет опыта', 'verbose_name_plural': 'Предметы опыта'},
        ),
        migrations.AddField(
            model_name='experienceitems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/items/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='experienceitems',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название'),
        ),
    ]
