# Generated by Django 4.2.7 on 2023-12-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_alter_experienceitems_options_experienceitems_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceitems',
            name='gold_for_use',
            field=models.IntegerField(blank=True, null=True, verbose_name='Плата за использование'),
        ),
        migrations.AlterField(
            model_name='experienceitems',
            name='experience_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество опыта'),
        ),
    ]
