# Generated by Django 4.2.7 on 2023-12-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_experienceitems_sale_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceitems',
            name='sale_now',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Продается'),
        ),
    ]
