# Generated by Django 4.2.7 on 2024-01-28 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_alter_cardstore_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0007_alter_historypurchaseitems_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmuletStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('bonus_hp', models.FloatField(verbose_name='Бонус здоровья')),
                ('bonus_damage', models.FloatField(verbose_name='Бонус урона')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('sale_now', models.BooleanField(default=True, verbose_name='Продажа')),
            ],
            options={
                'verbose_name': 'Амулет в магазине',
                'verbose_name_plural': 'Магазин амулетов',
            },
        ),
        migrations.AlterModelOptions(
            name='usersinventory',
            options={'verbose_name': 'Инвентарь предметов опыта', 'verbose_name_plural': 'Инвентари предметов опыта'},
        ),
        migrations.CreateModel(
            name='AmuletItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('bonus_hp', models.FloatField(verbose_name='Бонус здоровья')),
                ('bonus_damage', models.FloatField(verbose_name='Бонус урона')),
                ('rarity', models.CharField(max_length=3, verbose_name='Редкость')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card', verbose_name='Карта')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Амулет',
                'verbose_name_plural': 'Амулеты',
            },
        ),
    ]
