# Generated by Django 4.2.7 on 2024-01-29 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_amulettype_remove_amuletitem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amuletitem',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='amuletitem',
            name='sale_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Статус продажи'),
        ),
        migrations.AlterField(
            model_name='amuletitem',
            name='amulet_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange.amulettype', verbose_name='Тип амулета'),
        ),
        migrations.AlterField(
            model_name='amuletstore',
            name='amulet_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange.amulettype', verbose_name='Тип амулета'),
        ),
    ]
