# Generated by Django 4.2.7 on 2024-02-02 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_alter_cardstore_options'),
        ('exchange', '0011_alter_amuletitem_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amuletitem',
            name='sale_status',
        ),
        migrations.AlterField(
            model_name='amuletitem',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amulet_card', to='cards.card', verbose_name='Карта'),
        ),
    ]
