# Generated by Django 4.2.7 on 2024-02-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0013_amulettype_chance_drop_on_fight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amulettype',
            name='chance_drop_on_box',
            field=models.IntegerField(blank=True, null=True, verbose_name='Шанс выпадения в сундуке'),
        ),
    ]
