# Generated by Django 4.2.7 on 2024-02-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0015_experienceitems_chance_drop_on_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='amulettype',
            name='bonus_damage',
            field=models.FloatField(blank=True, null=True, verbose_name='Бонус урона'),
        ),
        migrations.AddField(
            model_name='amulettype',
            name='bonus_hp',
            field=models.FloatField(blank=True, null=True, verbose_name='Бонус здоровья'),
        ),
        migrations.AddField(
            model_name='amulettype',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='amulettype',
            name='sale_now',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Продажа'),
        ),
        migrations.DeleteModel(
            name='AmuletStore',
        ),
    ]
