# Generated by Django 4.2.7 on 2024-07-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0018_experienceitems_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='amulettype',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='amulettype',
            name='discount_now',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Действие скидки'),
        ),
    ]
