# Generated by Django 4.2.7 on 2024-07-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0024_delete_amuletrarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='amuletitem',
            name='upgrades',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество улучшений'),
        ),
    ]
