# Generated by Django 4.2.7 on 2024-07-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0029_amulettype_chance_drop_on_box_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmuletRarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('chance_drop_on_fight', models.IntegerField(blank=True, null=True, verbose_name='Шанс выпадения после битвы')),
                ('chance_drop_on_box', models.IntegerField(blank=True, null=True, verbose_name='Шанс выпадения в сундуке')),
                ('max_upgrade', models.IntegerField(blank=True, null=True, verbose_name='Максимальное количество улучшений')),
            ],
        ),
    ]
