# Generated by Django 4.2.7 on 2024-07-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0035_upgradeitemstype_amount_up_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgradeitemstype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/upgrade_items/', verbose_name='Изображение'),
        ),
    ]
