# Generated by Django 4.2.7 on 2025-09-16 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0038_upgradeitemsusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amuletitem',
            name='amulet_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amulet_type', to='exchange.amulettype', verbose_name='Тип амулета'),
        ),
    ]
