# Generated by Django 4.2.7 on 2025-09-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0039_alter_amuletitem_amulet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgradeitemstype',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена в магазине'),
        ),
        migrations.AddField(
            model_name='upgradeitemstype',
            name='price_of_use',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена использования'),
        ),
    ]
