# Generated by Django 4.2.7 on 2025-09-17 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0040_upgradeitemstype_price_upgradeitemstype_price_of_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgradeitemsusers',
            name='upgrade_item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_item_type', to='exchange.upgradeitemstype', verbose_name='Тип предмета улучшения'),
        ),
    ]
