# Generated by Django 4.2.7 on 2025-09-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0041_alter_upgradeitemsusers_upgrade_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialEventAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_event_visit', models.IntegerField(blank=True, null=True, verbose_name='День для получения награды')),
                ('type_award', models.CharField(blank=True, max_length=30, null=True, verbose_name='Тип награды')),
                ('amount_or_rarity_award', models.CharField(blank=True, max_length=30, null=True, verbose_name='Количество/Редкость(для карт) награды')),
                ('description', models.CharField(blank=True, max_length=30, null=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Награда начального ивента',
                'verbose_name_plural': 'Награды начального ивента',
            },
        ),
    ]
