# Generated by Django 4.2.7 on 2025-09-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0042_initialeventawards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialeventawards',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Дополнительная информация'),
        ),
    ]
