# Generated by Django 4.2.7 on 2025-10-01 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0026_card_max_merger_card_merger_and_more'),
        ('exchange', '0043_alter_initialeventawards_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amuletitem',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amulet_card', to='cards.card', verbose_name='Карта'),
        ),
    ]
