# Generated by Django 4.2.7 on 2025-10-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0044_alter_amuletitem_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initialeventawards',
            options={'verbose_name': 'Награда начального события', 'verbose_name_plural': 'Награды начального события'},
        ),
    ]
