# Generated by Django 4.2.7 on 2025-10-02 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0026_card_max_merger_card_merger_and_more'),
        ('exchange', '0045_alter_initialeventawards_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleEventAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(verbose_name='Место в рейтинге')),
                ('award', models.CharField(max_length=200, verbose_name='Тип награды')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Награда боевого события',
                'verbose_name_plural': 'Награды боевого события',
            },
        ),
        migrations.AlterField(
            model_name='amulettype',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Скидка %'),
        ),
        migrations.AlterField(
            model_name='amulettype',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='TeamsForBattleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_card_template', to='cards.card', verbose_name='Первая карта')),
                ('second_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_card_template', to='cards.card', verbose_name='Вторая карта')),
                ('third_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_card_template', to='cards.card', verbose_name='Третья карта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_template_event', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Шаблон отряда пользователя',
                'verbose_name_plural': 'Шаблоны отряда пользователей',
            },
        ),
        migrations.CreateModel(
            name='BattleEventParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemies', models.JSONField(blank=True, default=dict, null=True, verbose_name='Противники по дням')),
                ('battle_progress', models.JSONField(blank=True, default=dict, null=True, verbose_name='Прогресс по дням')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Очки')),
                ('first_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_card_team', to='cards.card', verbose_name='Первая карта')),
                ('second_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_card_team', to='cards.card', verbose_name='Вторая карта')),
                ('third_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_card_team', to='cards.card', verbose_name='Третья карта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_team_event', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Участник боевого события',
                'verbose_name_plural': 'Участники боевого события',
            },
        ),
    ]
