# Generated by Django 4.2.7 on 2025-10-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0046_battleeventawards_alter_amulettype_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersinventory',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество'),
        ),
    ]
