# Generated by Django 4.2.7 on 2023-12-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_fighthistory_options_fighthistory_card_loser_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleUserCards',
        ),
    ]
