# Generated by Django 4.2.7 on 2023-12-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_delete_saleusercards'),
    ]

    operations = [
        migrations.AddField(
            model_name='rarity',
            name='drop_chance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Шанс выпадения'),
        ),
    ]
