# Generated by Django 4.2.7 on 2023-12-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_type_better_type_worst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='damage',
            field=models.FloatField(verbose_name='Урон'),
        ),
        migrations.AlterField(
            model_name='card',
            name='hp',
            field=models.FloatField(verbose_name='Здоровье'),
        ),
    ]
