# Generated by Django 4.2.7 on 2024-01-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_alter_card_damage_alter_card_hp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardstore',
            options={'verbose_name': 'Карта в магазине', 'verbose_name_plural': 'Магазин карт'},
        ),
    ]
