# Generated by Django 4.2.7 on 2024-02-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_alter_cardstore_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcard',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='classcard',
            name='numeric_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Числовое значение'),
        ),
    ]
