# Generated by Django 4.2.7 on 2024-02-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_classcard_chance_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Уровень'),
        ),
    ]
