# Generated by Django 4.2.7 on 2024-02-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_alter_card_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcard',
            name='description_for_history_fight',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание для истории'),
        ),
    ]
