# Generated by Django 4.2.7 on 2023-12-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_experienceitems_gold_for_use_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceitems',
            name='sale_now',
            field=models.BooleanField(blank=True, null=True, verbose_name='Продается'),
        ),
    ]
