# Generated by Django 4.2.7 on 2023-12-20 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_alter_experienceitems_sale_now'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historypurchaseitems',
            options={'verbose_name': 'Покупка в магазине предметов', 'verbose_name_plural': 'Покупки в магазине предметов'},
        ),
    ]
