# Generated by Django 4.2.7 on 2024-01-30 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_alter_cardstore_options'),
        ('exchange', '0010_amuletitem_price_amuletitem_sale_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amuletitem',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.card', verbose_name='Карта'),
        ),
    ]
