# Generated by Django 4.2.7 on 2024-02-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0014_amulettype_chance_drop_on_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceitems',
            name='chance_drop_on_box',
            field=models.IntegerField(blank=True, null=True, verbose_name='Шанс выпадения в сундуке'),
        ),
    ]
