# Generated by Django 4.2.7 on 2024-02-06 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0016_amulettype_bonus_damage_amulettype_bonus_hp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amuletitem',
            name='bonus_damage',
        ),
        migrations.RemoveField(
            model_name='amuletitem',
            name='bonus_hp',
        ),
        migrations.RemoveField(
            model_name='amuletitem',
            name='price',
        ),
    ]
