# Generated by Django 4.2.7 on 2024-07-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0019_amulettype_discount_amulettype_discount_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amulettype',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Скидка %'),
        ),
    ]
