# Generated by Django 4.2.7 on 2024-07-26 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0023_remove_amuletitem_upgrades'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmuletRarity',
        ),
    ]
