# Generated by Django 4.2.7 on 2024-07-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0033_alter_amuletrarity_chance_drop_on_box_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeItemsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип предметов улучшения',
                'verbose_name_plural': 'Типы предметов улучшения',
            },
        ),
    ]
