# Generated by Django 4.2.7 on 2024-07-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0034_upgradeitemstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgradeitemstype',
            name='amount_up',
            field=models.IntegerField(blank=True, null=True, verbose_name='Значение улучшения характеристик'),
        ),
        migrations.AddField(
            model_name='upgradeitemstype',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='upgradeitemstype',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Тип предмета'),
        ),
    ]
