# Generated by Django 4.2.7 on 2024-07-30 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0037_alter_upgradeitemstype_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeItemsUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Количество')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('upgrade_item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange.upgradeitemstype', verbose_name='Тип предмета улучшения')),
            ],
            options={
                'verbose_name': 'Предмет улучшения в инвентаре пользователя',
                'verbose_name_plural': 'Предметы улучшения в инвентаре пользователя',
            },
        ),
    ]
