# Generated by Django 4.2.7 on 2023-12-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='experience_bar',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Опыт'),
        ),
        migrations.AddField(
            model_name='card',
            name='sale_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Продажа'),
        ),
    ]
