# Generated by Django 4.2.7 on 2023-12-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_experience_bar_card_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='price',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Цена продажи'),
        ),
    ]
