# Generated by Django 4.2.7 on 2023-12-04 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0004_fighthistory_saleusercards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fighthistory',
            options={'verbose_name': 'Бой', 'verbose_name_plural': 'Бои'},
        ),
        migrations.AddField(
            model_name='fighthistory',
            name='card_loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_loser', to='cards.card', verbose_name='Карта проигравшего'),
        ),
        migrations.AddField(
            model_name='fighthistory',
            name='card_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_winner', to='cards.card', verbose_name='Карта победителя'),
        ),
        migrations.AddField(
            model_name='fighthistory',
            name='date_and_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время'),
        ),
        migrations.AddField(
            model_name='fighthistory',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loser', to=settings.AUTH_USER_MODEL, verbose_name='Проигравший'),
        ),
        migrations.AddField(
            model_name='fighthistory',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL, verbose_name='Победитель'),
        ),
    ]
