# Generated by Django 4.2.7 on 2023-12-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_historyreceivingcards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyreceivingcards',
            options={'verbose_name': 'Создание карты', 'verbose_name_plural': 'Создание карт'},
        ),
    ]
