# Generated by Django 4.2.7 on 2023-12-08 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_alter_historyreceivingcards_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='better',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='better_vs', to='cards.type', verbose_name='Лучше против'),
        ),
        migrations.AddField(
            model_name='type',
            name='worst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worst_vs', to='cards.type', verbose_name='Хуже против'),
        ),
    ]
