# Generated by Django 4.2.7 on 2024-07-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0019_alter_card_merger'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardstore',
            name='discount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='cardstore',
            name='discount_now',
            field=models.BooleanField(blank=True, default=False, verbose_name='Действие скидки'),
        ),
    ]
