# Generated by Django 4.2.7 on 2024-07-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0020_cardstore_discount_cardstore_discount_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardstore',
            name='discount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Скидка %'),
        ),
    ]
