# Generated by Django 4.2.7 on 2025-09-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0021_alter_cardstore_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='max_mwrger',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Максимальное количество слияний'),
        ),
    ]
