# Generated by Django 4.2.7 on 2025-09-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0022_card_max_mwrger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='max_mwrger',
            field=models.IntegerField(blank=True, default=20, null=True, verbose_name='Максимальное количество слияний'),
        ),
    ]
