# Generated by Django 4.2.7 on 2025-09-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0023_alter_card_max_mwrger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='max_mwrger',
            new_name='max_merger',
        ),
    ]
