# Generated by Django 4.2.7 on 2025-10-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0024_rename_max_mwrger_card_max_merger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='max_merger',
        ),
        migrations.RemoveField(
            model_name='card',
            name='merger',
        ),
        migrations.AddField(
            model_name='card',
            name='enhancement',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество усилений'),
        ),
        migrations.AddField(
            model_name='card',
            name='max_enhancement',
            field=models.IntegerField(blank=True, default=20, null=True, verbose_name='Максимальное количество усилений'),
        ),
    ]
