# Generated by Django 4.2.7 on 2025-10-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0025_remove_card_max_merger_remove_card_merger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='max_merger',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='Максимальное количество слияний'),
        ),
        migrations.AddField(
            model_name='card',
            name='merger',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество слияний'),
        ),
        migrations.AlterField(
            model_name='card',
            name='experience_bar',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Текущий опыт'),
        ),
    ]
