# Generated by Django 4.2.7 on 2025-10-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0026_card_max_merger_card_merger_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('theme', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тема')),
                ('text', models.CharField(max_length=2000, verbose_name='Текст')),
                ('redirect_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка')),
                ('redirect_params', models.JSONField(blank=True, default=dict, null=True, verbose_name='Параметры ссылки')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
