# Generated by Django 4.2.7 on 2025-10-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0027_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_time_create',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время создания'),
        ),
    ]
