# Generated by Django 4.2.7 on 2025-10-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0028_news_date_time_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='redirect_name',
        ),
        migrations.RemoveField(
            model_name='news',
            name='redirect_params',
        ),
    ]
